### ISSUE TITLE
Blocks of type "required_providers" are not expected here

### ISSUE THREAD

**Issue by skyzyx** [thazelart/terraform-validator#50]
Firstly, this is a great tool. I use it constantly for a large number of Terraform modules I maintain. Thank you!

In my `versions.tf` file, I have a block which looks like this:

```hcl
# https://www.terraform.io/docs/configuration/terraform.html
terraform {
  required_version = ">= 0.12"

  required_providers {
    aws      = "~> 2.67"
    newrelic = "~> 1.19"
  }
}
```

A truncated version of my `.terraform-validator.yaml` file looks like this:

```yaml
layers:
  default:
    files:
      versions.tf:
        mandatory: true
        authorized_blocks:
          - required_providers # only added this after receiving the error message; it didn't help
          - terraform
```

When I run the tool, I get this message:

```bash
$ terraform-validator .
2020/07/03 01:07:04 versions.tf:5,3-21: Unsupported block type; Blocks of type "required_providers" are not expected here.
```

The `required_providers` sub-block of a `terraform` block is documented here: https://www.terraform.io/docs/configuration/terraform.html#specifying-required-provider-versions

How do I get `terraform-validator` to allow/enforce this block without throwing an error?
