### ISSUE TITLE
Allow existence check of a non *.tf file

### ISSUE THREAD

**Issue by jvanan24** [thazelart/terraform-validator#65]
Hi,

It seems terraform-validator is unable to check if a non *.tf file exists : 

```
 layers:
   default:
     files:
       README.md:
         mandatory: true
```
```
 terraform-validator .
INFO: running on terraform/meta with default configuration
ERROR: missing mandatory file(s):
  - README.md
```

```
ls -1  terraform/meta/README.md
terraform/meta/README.md
```

In this sample, it good be interesting to ensure that a README.md file exists
