### ISSUE TITLE
Enforce presence of a block in a file 

### ISSUE THREAD

**Issue by Ameausoone** [thazelart/terraform-validator#67]
It would be interesting to enforce that a file exist and then that a block is present inside. 

e.g. : 
Enforce presence of `provider` block only `providers.tf`file. 

Configuration could be like this : 

```
 layers:
   default:
     files:
       main.tf:
         mandatory: true
         authorized_blocks:
       providers.tf:
         mandatory: true
         exclusive_blocks:
           - provider
```
